# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Java project to Azure Function App - hazeng-fa-dc-java8-con

on:
  push:
    branches:
      - master

env:
  AZURE_FUNCTIONAPP_NAME: hazeng-fa-dc-java8-con # set this to your function app name on Azure
  POM_XML_DIRECTORY: '.' # set this to the directory which contains pom.xml file
  POM_FUNCTIONAPP_NAME: hazeng-fa-dc-java8-con # set this to the function app name in your local development environment
  JAVA_VERSION: '8' # set this to the java version to use

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: Setup Java Sdk ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}

    - name: 'Restore Project Dependencies Using Mvn'
      shell: pwsh
      run: |
        pushd './${{ env.POM_XML_DIRECTORY }}'
        mvn clean package
        mvn azure-functions:package
        popd
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: 'hazeng-fa-dc-java8-con'
        slot-name: 'production'
        package: './${{ env.POM_XML_DIRECTORY }}/target/azure-functions/${{ env.POM_FUNCTIONAPP_NAME }}'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_845044c8f2114952a84d23ebab173d6d }}